# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'HealthTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthTracker
  pod 'Alamofire', '~> 5.5'
end

